import { Auth0Provider } from '@auth0/nextjs-auth0';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Image from 'next/image';
import Link from 'next/link';
import { auth0 } from '../lib/auth0';
import './globals.css';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth0.getSession();

	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<header className="sticky top-0 z-40 flex w-full items-center justify-between gap-6 border-b border-slate-700 bg-slate-900/70 px-6 py-4 backdrop-blur supports-[backdrop-filter]:bg-slate-900/60">
					<div className="flex items-center gap-3">
						<Image src="/auth0.svg" alt="Auth0" width={32} height={32} className="drop-shadow" />
						<h1 className="text-xl font-semibold tracking-tight">Auth Demo (Next)</h1>
					</div>
					<nav className="hidden items-center gap-6 text-sm md:flex">
						<ul className="flex items-center gap-6">
							<li>
								<Link
									href="/"
									className="font-medium text-slate-600 transition-colors hover:text-slate-300 dark:text-slate-300 dark:hover:text-white"
								>
									Home
								</Link>
							</li>
							<li>
								<Link
									href="/dashboard"
									className="font-medium text-slate-600 transition-colors hover:text-slate-300 dark:text-slate-300 dark:hover:text-white"
								>
									Dashboard
								</Link>
							</li>
						</ul>
					</nav>
					<div className="flex items-center gap-3">
						{session?.user ? (
							<a
								href={`/auth/logout?returnTo=${encodeURIComponent(process.env.APP_BASE_URL!)}`}
								className="rounded-md bg-gradient-to-r from-slate-700 to-slate-600 px-5 py-2 text-sm font-medium text-slate-100 shadow-sm ring-1 ring-inset ring-slate-700 transition hover:from-slate-600 hover:to-slate-500"
							>
								Logout
							</a>
						) : (
							<a
								href={`/auth/login?returnTo=${encodeURIComponent(process.env.APP_BASE_URL!)}`}
								className="relative overflow-hidden rounded-md bg-gradient-to-r from-indigo-600 via-violet-600 to-fuchsia-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:brightness-110 focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400"
							>
								Login
							</a>
						)}
					</div>
				</header>
				<Auth0Provider user={session?.user}>{children}</Auth0Provider>
			</body>
		</html>
	);
}
